import ColorModeToggleButton from "@/components/ColorModeToggleButton";
import DarkModeToggleProvider from "@/context/DarkModeToggleProvider";
import TranslationContextProvider from "@/context/TranslationContextProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./Footer";
import "./globals.css";
import Navbar from "./Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkModeToggleProvider>
          <TranslationContextProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
            <ColorModeToggleButton />
          </TranslationContextProvider>
        </DarkModeToggleProvider>
      </body>
    </html>
  );
}
